### ISSUE TITLE
pip install pynumpress

### ISSUE THREAD

**Issue by IonGuide** [mobiusklein/pynumpress#3]
This doesn't work on Mac.. sorry if this is a stupid question, but from what I've read, the wheel might be windows-specific. Is there a good tutorial to install this on a Mac without pip somewhere? I guess that would be installing from source with Cython and a C++ compiler

**Comment by mobiusklein** [comment]
I don't have a Mac system to test on. Could you post the error message (and the build log) you're getting please?

**Comment by IonGuide** [comment]
So, I've had a breakthrough which was very lucky as I only vaguely know what I'm doing. Below was the output upon failure. It failed to "build the wheel". This seemed to be down to the use of the incorrect built in library to do with C++. Some more searching showed me that the MACOSX_DEPLOYMENT_TARGET environment variable was set at 10.7... I think that this was too low. I tried to change it with a terminal command (no idea if this actually worked as it still reads the same as far as I can tell): export MACOSX_DEPLOYMENT_TARGET = 10.9

I tried pip install pynumpress again and it worked. So.. I got lucky. Thanks for the quick reply =] 

Collecting pynumpress
  Using cached https://files.pythonhosted.org/packages/af/12/b0d2f159df79afc31606e8377761b08cb0735d6749e999b3c7662f6076f1/pynumpress-0.0.4.tar.gz
Requirement already satisfied: numpy in ./anaconda3/lib/python3.6/site-packages (from pynumpress) (1.16.0)
Building wheels for collected packages: pynumpress
  Building wheel for pynumpress (setup.py) ... error
  Complete output from command /Users/steve/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/_r/nfw0044x1497slf0v6l4pdsr0000gn/T/pip-install-pc8hsn6x/pynumpress/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/_r/nfw0044x1497slf0v6l4pdsr0000gn/T/pip-wheel-ja22h2tz --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.6
  creating build/lib.macosx-10.7-x86_64-3.6/pynumpress
  copying pynumpress/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/pynumpress
  running build_ext
  building 'pynumpress.pynumpress' extension
  creating build/temp.macosx-10.7-x86_64-3.6
  creating build/temp.macosx-10.7-x86_64-3.6/pynumpress
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/steve/anaconda3/include -arch x86_64 -I/Users/steve/anaconda3/include -arch x86_64 -I./pynumpress -I/Users/steve/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/Users/steve/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/Users/steve/anaconda3/include/python3.6m -c pynumpress/pynumpress.cpp -o build/temp.macosx-10.7-x86_64-3.6/pynumpress/pynumpress.o
  warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  pynumpress/pynumpress.cpp:630:10: fatal error: 'ios' file not found
  #include "ios"
           ^~~~~
  1 warning and 1 error generated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pynumpress
  Running setup.py clean for pynumpress
Failed to build pynumpress
Installing collected packages: pynumpress
  Running setup.py install for pynumpress ... error
    Complete output from command /Users/steve/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/_r/nfw0044x1497slf0v6l4pdsr0000gn/T/pip-install-pc8hsn6x/pynumpress/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/_r/nfw0044x1497slf0v6l4pdsr0000gn/T/pip-record-7jdv_i59/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.6
    creating build/lib.macosx-10.7-x86_64-3.6/pynumpress
    copying pynumpress/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/pynumpress
    running build_ext
    building 'pynumpress.pynumpress' extension
    creating build/temp.macosx-10.7-x86_64-3.6
    creating build/temp.macosx-10.7-x86_64-3.6/pynumpress
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/steve/anaconda3/include -arch x86_64 -I/Users/steve/anaconda3/include -arch x86_64 -I./pynumpress -I/Users/steve/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/Users/steve/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/Users/steve/anaconda3/include/python3.6m -c pynumpress/pynumpress.cpp -o build/temp.macosx-10.7-x86_64-3.6/pynumpress/pynumpress.o
    warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    pynumpress/pynumpress.cpp:630:10: fatal error: 'ios' file not found
    #include "ios"
             ^~~~~
    1 warning and 1 error generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Users/steve/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/_r/nfw0044x1497slf0v6l4pdsr0000gn/T/pip-install-pc8hsn6x/pynumpress/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/_r/nfw0044x1497slf0v6l4pdsr0000gn/T/pip-record-7jdv_i59/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/_r/nfw0044x1497slf0v6l4pdsr0000gn/T/pip-install-pc8hsn6x/pynumpress/

**Comment by IonGuide** [comment]
Actually, it looks like this may be a problem associated with the Conda distribution:
https://github.com/conda/conda-build/issues/1269

**Comment by mobiusklein** [comment]
Hmm. I don't think this is related to `conda-build` since the `conda` package manager isn't being invoked here. 

The error you're hitting is localized here:
```
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
pynumpress/pynumpress.cpp:630:10: fatal error: 'ios' file not found
#include "ios"
^~~~~
1 warning and 1 error generated.
error: command 'gcc' failed with exit status 1
```
If I had to guess, this is a compiler toolchain configuration problem. I'm not terribly familiar with the situation on Macs. I know more recent Mac systems will alias `clang` as `gcc` for compatibility. Based upon error message similarity from https://github.com/pandas-dev/pandas/issues/23424, could you try the steps listed there to check if your C++ compiler can be updated and if that fixes the problem?

**Comment by IonGuide** [comment]
You're right, I think. It's not that Conda is being invoked, it's that upon installation, Conda sets MACOSX_DEPLOYMENT_TARGET to 10.6. This seems to inhibit access to stdlibc++ for some strange reason. That prevents compilation of this package as it needs C++, I think. That means it doesn't affect some other packages, which is why it seemed to be a pynumpress issue to me. 

In any case, passing export MACOSX_DEPLOYMENT_TARGET=10.9 in terminal actually does change the variable (this can be checked by passing env and looking at the variable setting, it does change). When that variable is changed, access to the library isn't inhibited anymore and the wheel can be built properly! Exactly why this works, I don't know, but it's done the trick for me.

**Comment by mobiusklein** [comment]
Thank you for going through the labor of testing and debugging your local environment.

I suspect this is a recurrent issue for Cython-derived C++ extensions, given the number of people referencing the investigation in that issue I linked.

Since this appears to have fixed the problem, I'll close this issue.
